package cn.dancingsnow.appeu.registry;

import static bartworks.util.BWUtil.subscriptNumbers;

import org.apache.commons.lang3.tuple.Pair;

import bartworks.API.WerkstoffAdderRegistry;
import bartworks.system.material.Werkstoff;
import cn.dancingsnow.appeu.Config;
import gregtech.api.enums.Materials;
import gregtech.api.enums.TextureSet;

public final class ModMaterials implements Runnable {

    public static final Werkstoff TitaniumAluminumCarbide = new Werkstoff(
        new short[] { 67, 44, 64 },
        "Titanium Aluminum Carbide",
        subscriptNumbers("Ti3AlC2"),
        new Werkstoff.Stats().setMeltingPoint(2373)
            .setBlastFurnace(true)
            .disableAutoGeneratedBlastFurnaceRecipes(),
        Werkstoff.Types.COMPOUND,
        new Werkstoff.GenerationFeatures().disable()
            .onlyDust()
            .addMolten()
            .addMetalItems(),
        Config.materialIdStart,
        TextureSet.SET_METALLIC,
        Pair.of(Materials.Titanium, 3),
        Pair.of(Materials.Aluminium, 1),
        Pair.of(Materials.Carbon, 2));

    public static final Werkstoff MultilayerTitaniumCarbideMXene = new Werkstoff(
        new short[] { 45, 50, 55 },
        "Multilayer Titanium Carbide MXene",
        subscriptNumbers("Ti3C2Tx"),
        new Werkstoff.Stats(),
        Werkstoff.Types.COMPOUND,
        new Werkstoff.GenerationFeatures().disable()
            .onlyDust(),
        Config.materialIdStart + 1,
        TextureSet.SET_DULL,
        Pair.of(Materials.Titanium, 3),
        Pair.of(Materials.Carbon, 2));

    public static final Werkstoff DimethylSulfoxide = new Werkstoff(
        new short[] { 210, 225, 235 },
        "Dimethyl Sulfoxide",
        subscriptNumbers("C2H6OS"),
        new Werkstoff.Stats().setMeltingPoint(292)
            .setBoilingPoint(462),
        Werkstoff.Types.COMPOUND,
        new Werkstoff.GenerationFeatures().disable()
            .addCells(),
        Config.materialIdStart + 2,
        TextureSet.SET_FLUID,
        Pair.of(Materials.Carbon, 2),
        Pair.of(Materials.Hydrogen, 6),
        Pair.of(Materials.Oxygen, 1),
        Pair.of(Materials.Sulfur, 1));

    public static final Werkstoff IntercalatedTitaniumCarbideMXeneSlurry = new Werkstoff(
        new short[] { 60, 65, 75 },
        "Intercalated Titanium Carbide MXene Slurry",
        subscriptNumbers("Ti3C2Tx?C2H6OS?") + "??",
        new Werkstoff.Stats(),
        Werkstoff.Types.MIXTURE,
        new Werkstoff.GenerationFeatures().disable()
            .addCells(),
        Config.materialIdStart + 3,
        TextureSet.SET_FLUID,
        Pair.of(MultilayerTitaniumCarbideMXene, 1),
        Pair.of(DimethylSulfoxide, 1));

    public static final Werkstoff DelaminatedTitaniumCarbideMXeneSlurry = new Werkstoff(
        new short[] { 30, 35, 45 },
        "Delaminated Titanium Carbide MXene Slurry",
        subscriptNumbers("Ti3C2Tx?") + "??",
        new Werkstoff.Stats(),
        Werkstoff.Types.MIXTURE,
        new Werkstoff.GenerationFeatures().disable()
            .addCells(),
        Config.materialIdStart + 4,
        TextureSet.SET_FLUID,
        Pair.of(MultilayerTitaniumCarbideMXene, 1));

    public static void register() {
        WerkstoffAdderRegistry.addWerkstoffAdder(new ModMaterials());
    }

    @Override
    public void run() {}
}
